name: First Work Flow
on : workflow_dispatch
jobs :
  first-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello world"
      - name: Print goodbye
        run: echo "Done Goodbye"
        
